code/forum/urls.py
from django.urls import path, re_path

from . import views

app_name='forum'

urlpatterns = [
    path('<str:filt>', views.forum,name='forum'),
    path('<int:id>:<str:roll>?<int:textroll>/<str:filt>',views.forum_post,name='forum_post'),
    path('create/<str:filt>',views.create_post,name='create_post'),
    path('save_star/<int:id>/<int:roll>/<str:filt>',views.save_star,name='save_star'),
    path('<int:id>/<int:roll>/:<int:textroll>/<str:filt>',views.save_comment,name='save_comment')
]

code/quiz/urls.py
from django.urls import path

from . import views

app_name='quiz'

urlpatterns = [
    path('index/', views.userface,name='userface'),
    path('assignment/',views.assignment, name='assignment'),
    path('quiz/<int:question_id>/', views.quiz_new, name='quiz_new'),
    path('index/<int:question_id>/checking/', views.check, name='check'),
    path('account/',views.account, name='account'),
    path('admin/',views.admin,name='admin')  ,
    path('admin/assignment',views.admin_assignment,name='admin_assignment'),
    path('admin/quiz/<str:week>',views.admin_quiz,name='admin_quiz'),
    path('message/',views.message,name='message')
]

code/repolab/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("simple_judge.urls")),
    path('cs201/', include('quiz.urls')),
    path('cs201/forum',include('forum.urls'))
    ]

code/simple_judge/urls.py
from django.urls import path

from . import views

app_name='simple_judge'

urlpatterns = [
    path("", views.index, name="index"),
    path('signin',views.signin,name='signin'),
    path('signout',views.signout,name='signout'),
    path('change_password',views.change_password,name='change_password'),
]

code/forum/models.py
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    text=models.TextField()
    author_name= models.CharField(max_length=50)
    author_netid = models.CharField(max_length=8)
    pub_date = models.DateTimeField(default=datetime.datetime.strptime('2022-7-26 6:00','%Y-%m-%d %H:%M').astimezone(datetime.timezone(datetime.timedelta(hours=0))))
    title = models.CharField(max_length=100)
    level = models.IntegerField(default=0) # Asynchorons or Shown to everyone 
    question_id = models.IntegerField(default=0) #
    category = models.IntegerField(default=0) # This is the week id 
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    author_name = models.CharField(max_length=50)
    author_netid = models.CharField(max_length=8)
    pub_date = models.DateTimeField(default=datetime.datetime.strptime('2022-7-26 6:00','%Y-%m-%d %H:%M').astimezone(datetime.timezone(datetime.timedelta(hours=0))))
    reply = models.IntegerField(default=-1)
    def __str__(self):
        return self.text

code/forum/views.py
from django.shortcuts import render
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
)

from django.urls import reverse
from simple_judge.models import Student, Questiondict
from forum.models import Comment, Post


import datetime
from django.db.models import Q
import os
from repolab.settings import BASE_DIR

## This is online img path
savedir = os.path.join(BASE_DIR,'static/forum/images/')

## This is local img path
#savedir = os.path.join(BASE_DIR,'forum/static/forum/images/')
# Create your views here.

def record_online_time(minute = 30):
    tim = datetime.datetime.utcnow().astimezone(datetime.timezone(datetime.timedelta(hours=0))) #UTC Time
    return tim, tim+datetime.timedelta(minutes=minute)

def userface(request):
    return HttpResponse("Hello")

def forum(request,filt):
    context={}

    
    student = Student.objects.get(student_netid=request.user.username)
    student.online_time, student.offline_time  = record_online_time()     
    student.save()

    post_seen = list(map(int,list(filter(lambda x:x!='',student.forum_seen.split(',')))))
    comment_seen = list(map(int,(list(filter(lambda x: x!="", student.comment_seen.split(','))))))
    post_star = list(map(int,(list(filter(lambda x: x!="", student.forum_star.split(','))))))

    ## Second level filter 

    if filt == 'All':
        context['post']=Post.objects.all().order_by('-pub_date')
        
    elif filt =='Star':

        post = [Post.objects.get(id=star_id) for star_id in post_star]
        context['post']= post
    
    elif filt[0:2]=='We':
        week = int(filt[4:])
        context['post'] = Post.objects.filter(question_id__gte=week*100 ,question_id__lte=(week+1)*100).order_by('-pub_date')
        context['first']=filt
        context['problem'] = Questiondict.objects.filter(question_id__gte=week*100 ,question_id__lte=(week+1)*100).order_by('question_id')

    else :
        question_id = int(filt)
        week = int(filt[0:1])
        context['post'] = Post.objects.filter(question_id=question_id).order_by('-pub_date') 
        context['problem']=Questiondict.objects.filter(question_id__gte=100*week,question_id__lte=100*(week+1)).order_by('question_id')
        context['first']="Week"+str(week)
    

    context['post_star']=post_star
    context['post_seen']=post_seen

    context['filt']=filt
    context['comment_seen']= [Comment.objects.get(id=comment_id).post_id for comment_id in comment_seen]
    return render(request, 'forum/forum.html',context)

def forum_post(request, id, roll,textroll,filt):
    
    roll = int(float(roll))
    context={}
    current_post = Post.objects.get(id=id)

    student = Student.objects.get(student_netid=request.user.username)
    
    student.online_time, student.offline_time  = record_online_time()     
    student.save()


    # post_seen is actually post unseen
    if student.forum_seen.find(str(id)+',')!=-1:
        student.forum_seen=student.forum_seen.replace(str(id)+',','')
        student.save()


    post_seen = list(map(int,(list(filter(lambda x: x!="", student.forum_seen.split(','))))))
    post_star = list(map(int,(list(filter(lambda x: x!="", student.forum_star.split(','))))))
    comment_seen = list(map(int,(list(filter(lambda x: x!="", student.comment_seen.split(','))))))
    message_seen = list(map(int,(list(filter(lambda x: x!="", student.messages.split(','))))))
    context['new_comment'] = comment_seen

    # delete the comment in commen seen 
    if(roll!=-1):
        for comment_id in comment_seen:
            if Comment.objects.get(id=comment_id) in Comment.objects.filter(post_id=id):
                student.comment_seen = student.comment_seen.replace(str(comment_id)+',','')

        for message_id in message_seen:
            if Comment.objects.get(id=message_id) in Comment.objects.filter(post_id=id):
                student.messages = student.messages.replace(str(message_id)+',','')
        
        student.save()

    comment_seen = list(map(int,(list(filter(lambda x: x!="", student.comment_seen.split(','))))))

    if filt == 'All':
        context['post']=Post.objects.all().order_by('-pub_date')
        
    elif filt =='Star':

        post = [Post.objects.get(id=star_id) for star_id in post_star]
        context['post']= post
    
    elif filt[0:2]=='We':
        week = int(filt[4:])
        context['post'] = Post.objects.filter(question_id__gte=week*100 ,question_id__lte=(week+1)*100).order_by('-pub_date')
        context['first']=filt
        context['problem'] = Questiondict.objects.filter(question_id__gte=week*100 ,question_id__lte=(week+1)*100).order_by('question_id')

    else :
        question_id = int(filt)
        week = int(filt[0:1])
        context['post'] = Post.objects.filter(question_id=question_id).order_by('-pub_date') 
        context['problem']=Questiondict.objects.filter(question_id__gte=100*week,question_id__lte=100*(week+1)).order_by('question_id')
        context['first']="Week"+str(week)

    context['current']=current_post

    context['filt']=filt

    context['text']=current_post.text
    context['post_seen']=post_seen
    context['roll'] = roll
    context['post_star']=post_star
    context['text_roll']=textroll
    context['comment_seen']=[Comment.objects.get(id=comment_id).post_id for comment_id in comment_seen] # This is actually the post id 
    
    
    comment = current_post.comment_set.filter(reply=-1)
    context['comment_length']=comment.count()
    reply_array = current_post.comment_set.filter(~Q(reply=-1))
    reply=[]

    for c in comment:
        re = list(filter(lambda x: x.reply==c.id, reply_array))
        reply.append(re)
    
    context['comment_and_reply']=list(zip(comment,reply))
    

    return render(request, 'forum/forum_post.html', context)



def create_post(request,filt):
    
    if request.method=="POST":
        text = request.POST['text']
        img_length=request.POST['img_length']

        title  = request.POST['title']
        level= int(request.POST['level'])
        category = int(request.POST['category'])
        problem = int(request.POST['question_input'])
        question_id = (category+1)*100+problem
        author =  Student.objects.get(student_netid=request.user.username)
        author.online_time, author.offline_time  = record_online_time()     
        author.save()
        author_name = author.student_name
        author_netid = author.student_netid
        time_now = datetime.datetime.utcnow()+datetime.timedelta(hours=8)
        pub_date = time_now.astimezone(datetime.timezone(datetime.timedelta(hours=0))) #utc+8 now
        p = Post(text=text, title=title, author_name = author_name, pub_date=pub_date,level=level,category=category,author_netid=author_netid,question_id=question_id)
        p.save()

        if img_length !='0':
            #return HttpResponse(request.FILES.get('0img').name)
            for i in range(0,int(img_length)):
                img_title = str(i)+'img'
                ## imgfile
                img = request.FILES.get(img_title)
                ## savedir

                # student_netid + post_id + img.name
                # example : bt132_10_HelloWorld.jpg
                

                back = img.name[img.name.find('.'):]

                img_name = request.user.username +'_'+str(p.id)+'_'+datetime.datetime.strftime(time_now,'%Y-%m-%d-%H-%M-%S')+'_'+str(i)+'_'+back


                img_path = os.path.join(savedir, img_name)
                with open(img_path, 'wb') as fp:
                    for chunk in img.chunks():
                        fp.write(chunk)
                p.text=p.text+"\n\n"+"![image](/static/forum/images/"+img_name+")"
            p.save()

        for student in Student.objects.all():
            student.forum_seen+=str(p.id)+','
            student.save()

        
        return HttpResponseRedirect(reverse('forum:forum', args=(filt,)))



    context={}
    context['post']=Post.objects.all().order_by('-pub_date')
    context['filt']=filt
    context['week_question_number'] = [ Questiondict.objects.filter(question_week =i ).count() for i in range(1,8)]

    return render(request, 'forum/create_post.html', context)




def save_star(request,id,roll,filt):

    if request.method=='POST':

        id=str(id)
        s = Student.objects.get(student_netid=request.user.username)
        s.online_time, s.offline_time  = record_online_time()     
        s.save()
        if s.forum_star.find(id+',')==-1:
            s.forum_star+=id+','
            s.save()
        else:
            s.forum_star=s.forum_star.replace(id+',','')
            s.save()


    return HttpResponseRedirect(reverse('forum:forum_post' ,args=(id,roll,0,filt,)) )


def save_comment(request, id, roll, textroll,filt):

    comment_text = request.POST['comment_text']
    reply=int(request.POST['comment_id'])
    author = Student.objects.get(student_netid=request.user.username)
    author.online_time, author.offline_time  = record_online_time()     
    author.save()
    author_name = author.student_name
    author_netid = author.student_netid
    pub_date = datetime.datetime.utcnow().astimezone(datetime.timezone(datetime.timedelta(hours=8))) #utc now

    post = Post.objects.get(id=id)
    comment = post.comment_set.create(text=comment_text, author_name=author_name, author_netid=author_netid, pub_date=pub_date,reply=reply)
    post.save()
    
    img_length = request.POST['img_length']

    if img_length != '0':
        
        for i in range(0,int(img_length)):
            img_title = str(i)+'img'

            img = request.FILES.get(img_title)
            ## savedir
            
            # student_netid + post_id +i + img.name
            # example : Alice_108_2022-08-13-19-27-55_1.png
            
            back = img.name[img.name.find('.'):]

            img_name = request.user.username +'_'+str(comment.id)+'_'+datetime.datetime.strftime(datetime.datetime.utcnow()+datetime.timedelta(hours=8),'%Y-%m-%d-%H-%M-%S')+'_'+str(i)+back

code/forum/templates/forum/create_post.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    {% comment %} <meta name="viewport" content="width=device-width+100, initial-scale=2.0"> {% endcomment %}
    <meta name="description" content="">
    <meta name="author" content="Beilong Tang">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Home Page</title>


{% load static %}
{% load my_tags%}

<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/css/bootstrap.min.css' %}">
<script type= "text/javascript" src = "{% static 'quiz/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<link rel = "stylesheet" type ="text/css" href = "{% static 'simple_judge/cover.css' %}">
<link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">
<script type= "text/javascript" src="{% static 'forum/sidebars.js' %}"></script>
<script type= "text/javascript"  src = "{% static 'quiz/function.js' %}"></script>
<script>function go(){var x = "{% url 'simple_judge:signout' %}";confirmation(x);}</script>
<style>
  .buttons:hover{
    background: rgb(204, 198, 198);
  }

  .buttons{
    background:white;
    border:none;
  }
</style>
<script>
  // href list; all the href goes here:
  var forum_url_All = "{%url 'forum:forum' 'All' %}";

  function cancel(){
    var x = document.getElementById('title');
    var y = document.getElementById('textarea');
    if (x.value!="" || y.value!=""){
      var x =confirm("Are you sure you want to cancel?")
      if(x==true){
        window.location.href=forum_url_All;
        return;
      }
      
    }
    window.location.href=forum_url_All;
    return;
  }
  var number = 0;
  function preview(width, height,id){
      var x = document.getElementById(id);
      console.log(x.value);
      var name = document.getElementById(id).files[0];
      if (window.URL != undefined && name){
          url = window.URL.createObjectURL(name);
      }
      var z = url;
      var y = document.getElementById(id+'imgPreview');
      
      if (x.value=="") {y.src="";y.width=0;y.height=0}
      else{y.width=width;y.height=height;y.src=z;}
  }
  function add(){
      var divBox = document.getElementById('mydiv');
      var newdiv = document.createElement('div');
      newdiv.class='image_and_preview';
      newdiv.style='margin-top:20px'
      newdiv.id = number+"image_and_preview";
      newdiv.innerHTML="<img id ='"+number+"imgPreview'  width='0' height='0'/> <input type='file' id='"+number+"' name='"+number+"img' accept='image/gif, image/jpeg, image/png, image/jpg' onchange='preview(100,100,this.id)' > <a ></a>";
      divBox.appendChild(newdiv);
      number++;
      img_length_update();
  }
  function del(){
      if (number!=0) number--;img_length_update();
      var x = document.getElementById(number+'image_and_preview');
      console.log(number+'--')
      x.parentNode.removeChild(x);
  }
  
  function check(){
      //if (number==0){alert('success'); return }
      if(number!=0) {
          for (var i =0; i < number;i++){
              var x = document.getElementById(i+'');
              if (x.value==""){
                  alert('you have unfinished images');
                  return;
              }
          }
      }
      if( document.getElementById('title').value=="") {alert('Your title is empty');return;}
      if( document.getElementById('textarea').value=="") {alert('Your text is empty');return;}
      if( document.getElementById('question_input').value==0) {alert('Please specify your problem');return;}
      document.getElementById('forum_form').submit()

  }

  function img_length_update(){
    var x = document.getElementById('img_length');
    x.value=number;
  }


</script>





    <!-- Custom styles for this template -->
    {% comment %} <link href="cover.css" rel="stylesheet"> {% endcomment %}
  </head>
  <body class="d-flex h-100 text-center text-black bg-white">
    
    <div class="container-fluid d-flex w-100 h-100  mx-auto flex-column">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
          <span class="fs-4">CS201 Forum</span>
        </a>
  
  
        <ul class="nav nav-pills">
          <li class="nav-item"><a href="{% url 'quiz:userface' %}" class="nav-link " aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'quiz:assignment'  %}" class="nav-link">Quizzes</a></li>
        <li class="nav-item"><a href="{% url 'quiz:account'  %}" class="nav-link">Account</a></li>
        <li class="nav-item"><a href="{% url 'quiz:message'  %}" class="nav-link">Message</a></li>
        <li class="nav-item"><a href="{% url 'forum:forum' 'All' %}" class="nav-link active">Forum</a></li>
        <li class="nav-item"><a href="#" class="nav-link" onclick="go()">Log out</a></li>
        </ul>
      </header>

    <main class="d-flex flex-nowrap">
        <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-purple scrollarea" style='margin:0 auto;width:1200px'>
            <div style="margin-left:20%;width:60%">
              <form action="{%url 'forum:create_post' filt %}" method="post" autocomplete='off' id='forum_form' enctype="multipart/form-data">
                    {% csrf_token%}
                    <label for="exampleFormControlInput1">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Your title goes here" name="title" autocomplete="off" spellcheck="false" required>
                          <div style="width:100%;"><label style="margin-left:0%;margin-top:10px;">Week </label></div>
                          <div style="margin-top:5px;margin-bottom:10px;margin-left:1px;width:100%">
                          <input type="radio" class="btn-check" name="category" id="option1" autocomplete="off" value ="0" checked='true' onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option1">Week1</label>
                          <input type="radio" class="btn-check" name="category" id="option2" autocomplete="off" value ="1" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option2">Week2</label>
                          <input type="radio" class="btn-check" name="category" id="option3" autocomplete="off" value ="2" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option3">Week3</label>
                          <input type="radio" class="btn-check" name="category" id="option4" autocomplete="off" value ="3" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option4">Week4</label>
                          <input type="radio" class="btn-check" name="category" id="option5" autocomplete="off" value ="4" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option5">Week5</label>
                          <input type="radio" class="btn-check" name="category" id="option6" autocomplete="off" value ="5" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option6">Week6</label>
                          <input type="radio" class="btn-check" name="category" id="option7" autocomplete="off" value ="6" onclick="show_category()">
                          <label class="btn btn-outline-primary" for="option7">Week7</label>
                          <p style ='margin-top:15px;font-size:12px;color:grey' id="show_category">Week1</p>
                          <script>

                            function show_category(){
                            var q = document.getElementById('question_dropdown');
                            var x = document.getElementsByName('category');
                            for (var i =0; i < x.length;i++){
                              if (x[i].checked){
                                  var y = x[i].value;
                                  break;
                              }
                            }
                            // alert(y==0)
                            var x =document.getElementById('show_category');
                            y=parseInt(y)+1;
                            x.innerText='Week'+y;
                            var tex = select(y,'{{week_question_number.0}}','{{week_question_number.1}}','{{week_question_number.2}}','{{week_question_number.3}}','{{week_question_number.4}}','{{week_question_number.5}}','{{week_question_number.6}}');
                            q.innerHTML=tex;

                            var x = document.getElementById('question_input');
                            x.value=0;
                            var p = document.getElementById('show_question');
                            p.innerText="Please specify your problem";
                            return;
                          }


                          function show_question(id){
                            var x = document.getElementById('question_input');
                            x.value=id;
                            var p = document.getElementById('show_question');
                            p.innerText='Problem'+id;
                          }
                            </script>
                            
                          </div>
                          
                    
                          <div class="dropdown" style='' id='week_problems'>
                            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                              Problem
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" style='max-height:250px; overflow-y:scroll;' id ='question_dropdown'>
                              
                              <li><button onclick='alert(1)' style='border:none;background:white' id='problem1'><a class='dropdown-item' href='#'>Problem1</a></button></li>
                            </ul>
                            <p style ='margin-top:15px;font-size:16px;color:grey' id="show_question">Please specify your question</p>
                            <input value =0 name='question_input' id = 'question_input' style='display:none'>
                          </div>
                    
                          <script>window.onload=show_category();</script>
                    <div class="form-group" style="margin-top:5px">
                      <label for="exampleFormControlTextarea1">Text</label>
                      <textarea class="form-control" id="textarea" rows="10" autocomplete='off' spellcheck='false' placeholder="Your text goes here" name ="text" required></textarea>
                    </div>
                    
                    <div>
                      <label for="" style='margin-bottom:10px'>Image</label>
                      <div id='mydiv'>
                        <button type = 'button' id ='nextbotton' class='btn btn-primary btn-sm' onclick="add()">Add</button>
                        <button type='button' id ='nextbotton'  class='btn btn-primary btn-sm' onclick="del()">Delete</button>
                      <input name='img_length' id='img_length' value=0 style='display:none'>
                        </div>
                    </div>



                        <div class="form-check form-check-inline" style="text-align:left;margin-top:10px">
                          <input type="radio" name="level" class="form-check-input" id="radio0" value="0" checked='true'>
                          <label class="form-check-label" for="exampleRadio1">Default<small class="text-muted">  (visible to everyone)</small> </label>
                        </div>
                        
                        <div class="form-check form-check-inline" style="text-align:left" >
                          <input type="radio" name="level" class="form-check-input" id="radio2" value="1">
                          <label class="form-check-label" for="exampleRadio1">Anonymous<small class="text-muted">  (hide your name)</small> </label>
                        </div>
                        {% comment %} <div class="form-check form-check-inline" style="text-align:left" >
                          <input type="radio" name="level" class="form-check-input" id="radio1" value="2">
                          <label class="form-check-label" for="exampleRadio1">Private <small class="text-muted">  (visible to you and staff)</small></label>
                        </div> {% endcomment %}

                        {% comment %}  {% endcomment %}
                        <div style="margin-top:10px">
                          <a style="width:250px;text-align:right;margin-right:100px"><button type="button" class="btn btn-primary btn-lg" style="margin-bottom:5px" onclick="cancel()">Cancel</button></a>
                          <a style="width:250px;text-align:left"><button type="button" class="btn btn-primary btn-lg" style="margin-bottom:5px" onclick="check()">Post</button></a>
                        </div>
                        {% comment %} hidden input {% endcomment %}
                    
              </form>
            
            </div>
        </div>
        
    </main>


  <footer class="mt-auto text-black-50" style="font-size:15px">
    <p>Supported by <a class="text-black">CS201 TA Team</a>. Contact Beilong Tang (<a class="text-black">bt132@duke.edu</a>) if you have problems.</p>
  </footer>
</div>


    
  </body>
</html>