code/forum/urls.py
from django.urls import path, re_path

from . import views

app_name='forum'

urlpatterns = [
    path('<str:filt>', views.forum,name='forum'),
    path('<int:id>:<str:roll>?<int:textroll>/<str:filt>',views.forum_post,name='forum_post'),
    path('create/<str:filt>',views.create_post,name='create_post'),
    path('save_star/<int:id>/<int:roll>/<str:filt>',views.save_star,name='save_star'),
    path('<int:id>/<int:roll>/:<int:textroll>/<str:filt>',views.save_comment,name='save_comment')
]

code/quiz/urls.py
from django.urls import path

from . import views

app_name='quiz'

urlpatterns = [
    path('index/', views.userface,name='userface'),
    path('assignment/',views.assignment, name='assignment'),
    path('quiz/<int:question_id>/', views.quiz_new, name='quiz_new'),
    path('index/<int:question_id>/checking/', views.check, name='check'),
    path('account/',views.account, name='account'),
    path('admin/',views.admin,name='admin')  ,
    path('admin/assignment',views.admin_assignment,name='admin_assignment'),
    path('admin/quiz/<str:week>',views.admin_quiz,name='admin_quiz'),
    path('message/',views.message,name='message')
]

code/repolab/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("simple_judge.urls")),
    path('cs201/', include('quiz.urls')),
    path('cs201/forum',include('forum.urls'))
    ]

code/simple_judge/urls.py
from django.urls import path

from . import views

app_name='simple_judge'

urlpatterns = [
    path("", views.index, name="index"),
    path('signin',views.signin,name='signin'),
    path('signout',views.signout,name='signout'),
    path('change_password',views.change_password,name='change_password'),
]

code/quiz/views.py
from django.shortcuts import render
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
)
#from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from simple_judge.models import Student, Question, Questiondict
from forum.models import Post, Comment
from django.contrib.auth.decorators import login_required
import quiz.utils as ut
import random
import datetime
from utils.settings import question_due_dict
from django.db.models import Q
# Create your views here.

mult_shuffle = True

def record_online_time(minute = 30):
    tim = datetime.datetime.utcnow().astimezone(datetime.timezone(datetime.timedelta(hours=0))) #UTC Time
    return tim, tim+datetime.timedelta(minutes=minute)


@login_required(login_url='/signin',redirect_field_name='/cs201/index')
def userface(request):
    student = Student.objects.get(student_netid = request.user.username)
    student.online_time, student.offline_time  = record_online_time()     
    student.save() 
    context={}
    context['session']=request.session.get('username')
    return render(request, 'quiz/problems.html',context)

@login_required(login_url='/signin')
def assignment(request):
    
    student=Student.objects.get(student_netid=request.user.username)
    student.online_time, student.offline_time  = record_online_time()     
    student.save() 
    context={}
    ## All the assignments that are between the pub_date and due_date
    question_due_dict= student.question_due_dict
    # filter the quiz that is not open, and show the quiz whose state is either open or passed  // open for 1, and passed for -1
    due_dict = ut.checktime(question_due_dict)
    
    progress_array, passed_array = ut.get_progress(student.question_set.all(),len(due_dict))

    set=[101,201,301,401,501,601,701]
    
    context['array']=list(zip( due_dict.keys(), due_dict.values(), progress_array, set,  passed_array))
    return render(request,'quiz/assignment.html',context)

@login_required(login_url='/signin')
def account(request):
    student=Student.objects.get(student_netid=request.user.username)
    student.online_time, student.offline_time  = record_online_time()     
    student.save() 
    context={}
    context['user'] = request.user
    context['student']=student
    context['admin']=Student.objects.get(student_netid=request.user.username).level>0
    return render(request, 'quiz/account.html', context)

@login_required(login_url='/signin')
def check(request, question_id):
    student_current=Student.objects.get(student_netid=request.user.username)
    quiz=student_current.question_set.get(question_id=question_id)
    if request.method=='POST':
        question_dict=Questiondict.objects.get(question_id=question_id)
        answer=ut.getanswer(request,len(question_dict.question_content.get('answers')),question_dict.question_type)
        quiz.logx+='#'.join(answer)+'@'+str(datetime.datetime.utcnow())[:19]+'$'
        quiz.save()
        if ut.checkanswer(answer,question_id,question_dict.question_type,request.user.username)!=True:    
            messages.error(request, 'Wrong Answer!')
            if quiz.submission_times > 0 and quiz.ifpassed==False:
                quiz.submission_times=quiz.submission_times-1
                quiz.seed=random.randint(0,100)
                quiz.save()
            return HttpResponseRedirect(reverse('quiz:quiz_new',args=(question_id,)))
        messages.success(request, 'Correct Answer!')
        if quiz.ifpassed==True:
            return HttpResponseRedirect(reverse('quiz:quiz_new', args=(question_id,)))
        if quiz.submission_times > 0:
            quiz.ifpassed=True
            quiz.save()
        return HttpResponseRedirect(reverse('quiz:quiz_new', args=(question_id, )))
    return HttpResponse('You are not allowed to see the page now')

@login_required(login_url='/signin',redirect_field_name='/content/assignment')
def quiz_new(request,question_id):
    
    student_current=Student.objects.get(student_netid=request.user.username)
    student_current.online_time, student_current.offline_time  = record_online_time()     
    student_current.save() 
    question_dict=Questiondict.objects.get(question_id=question_id)
    question_week=question_dict.question_week
    q= student_current.question_set.get(question_id=question_id)
    # quiz_description=question_dict.question_content.get('description')
    mult=True
    context={}

    time_array = student_current.question_due_dict.get("week"+str(question_week))
    time_start = datetime.datetime.strptime(time_array[0],'%Y-%m-%d %H:%M') # UTC+8
    time_end = datetime.datetime.strptime(time_array[1],'%Y-%m-%d %H:%M') # UTC+8
    time_now = datetime.datetime.utcnow()
    if time_now > time_end - datetime.timedelta(hours=8):
        context['overdue']=True
    elif time_now >= time_start- datetime.timedelta(hours=8):
        context['overdue']=False
        pass
    else:
        return HttpResponse("The question is not open yet")

    if question_dict.question_type=='blank' or question_dict.question_type=='code':
        answers=question_dict.question_content.get('answers')
        mult=False
        # if mult
    else:
        answers=ut.mult_answer_convert(question_dict.question_content.get('answers'))
        context['choices'] = ut.shuffle_choices(choices=question_dict.question_content.get('choices'),seed=q.seed,shuffle= not context['overdue'])
        try:
            context['description'] = question_dict.question_content.get('description') % "\n\n".join(context['choices'].values())
        except:
            context['description'] = question_dict.question_content.get('description').replace("%s","\n\n".join(context['choices'].values()))

    # Find latest history
    if q.logx!="":
        if q.logx.find("#^")==-1:
            answer_string_and_time = q.logx[q.logx.rfind('$',0,q.logx.rfind('$')-1)+1:]
            answer_sets  = answer_string_and_time[:answer_string_and_time.find('@')].split('#')
        else :
            answer_string_and_time = q.logx[q.logx.rfind('$',0,q.logx.rfind('$')-1)+1:]
            answer_sets  = answer_string_and_time[:answer_string_and_time.find('@')].split('#^')
        context['recent_answer']=answer_sets

        if mult:
            context['recent_answer']=""
            

    question_sets_temp1=student_current.question_set.filter(question_id__gte=100*question_week , question_id__lte=100*(question_week+1)).order_by('question_id')

    context['question_dict']=question_dict
    context['quiz']=q
    context['mult']=mult
    context['answers']=answers
    context['section']=question_dict.question_content.get('section')
    context['question_id']=question_id
    context['length']=len(question_sets_temp1)
    context['question_sets']=question_sets_temp1
    context['passed']=len(question_sets_temp1.filter(ifpassed=True))
    context['failed']=len(question_sets_temp1.filter(submission_times=0))
    context['ids']=ut.findid(question_id,len(question_sets_temp1))
    context['post_number'] = Post.objects.filter(question_id=question_id).count()
    return render(request, 'quiz/quiz.html', context)

@login_required(login_url='/signin')
def message(request):
    
    student = Student.objects.get(student_netid=request.user.username)


    if request.method=='POST':
        delete_msg_id = request.POST['delete']
        student.messages=student.messages.replace(delete_msg_id+',','')
        student.save()
        return HttpResponseRedirect(reverse('quiz:message',args=()))
    
    context={}
    ## including reply and messages
    message_id_arrays = list(map(int,(list(filter(lambda x: x!="", student.messages.split(','))))))

    post = []
    comment=[]
    ## if it is a reply
    reply=[]

    for msg_id in message_id_arrays:
        msg = Comment.objects.get(id=msg_id)
        if msg.reply!=-1:
            reply.append(Comment.objects.get(id=msg.reply).author_name)
        else:
            reply.append("")
        comment.append(msg)
        post.append(Post.objects.get(id=msg.post_id))
    
    context['post_and_comment']=list(zip(post,comment,reply))


    return render(request, 'quiz/message.html',context)
    pass


## Admin Page
@login_required(login_url='/signin')
def admin(request):
    #if request.user.username !='admin':
    if Student.objects.get(student_netid=request.user.username).level<1:
        return HttpResponse("You do not have the level to see this page, so you cannot see the page")
    


    tim = datetime.datetime.utcnow().astimezone(datetime.timezone(datetime.timedelta(hours=0))) # UTC Time
    online_people_array = Student.objects.filter(offline_time__gte=tim).filter(level=0)
    context={}
    #context['online']=online_people_array
    context['online_number']=online_people_array.count()


    return render(request, 'quiz/admin.html',context)

@login_required(login_url='/signin')
def admin_assignment(request):
    if Student.objects.get(student_netid=request.user.username).level<1:
        return HttpResponse("You do not have the level to see this page, so you cannot see the page")
    
    context={}

    # context['quiz_due_dict']=question_due_dict
    #                                   i                            j
    # context['array']=list(zip(question_due_dict.keys(), question_due_dict.values()))

    # Finished people number
    s_array = Student.objects.filter(level=0)
    context['student_number'] = s_array.count()
    array_pass_num =[]
    array_almost_pass_num =[]
    array_passed_rate_percentage=[]
    array_submit_times=[]


    for i in range(1,8):
        student_pass_num = 0
        student_almost_pass_num = 0
        pass_question = 0
        pass_and_fail = 0
        submit_times = 0

        for s in Student.objects.filter(level=0):

            question_array = s.question_set.filter(question_id__gte=100*i , question_id__lte=100*(i+1))
            pass_and_fail_array =  question_array.filter( Q(ifpassed=True) | Q(submission_times=0))

code/quiz/templates/quiz/account.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    {% comment %} <meta name="viewport" content="width=device-width+100, initial-scale=2.0"> {% endcomment %}
    <meta name="description" content="">
    <meta name="author" content="Beilong Tang">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Account</title>


{% load static %}
{% load my_tags%}

<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/css/bootstrap.min.css' %}">
<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/js/bootstrap.bundle.min.js' %}">
<link rel = "stylesheet" type ="text/css" href = "{% static 'simple_judge/cover.css' %}">
<script type= "text/javascript"  src = "{% static 'quiz/function.js' %}"></script>
<script>function go(){var x = "{% url 'simple_judge:signout' %}";confirmation(x);}</script>
<link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">

    <!-- Custom styles for this template -->
    {% comment %} <link href="cover.css" rel="stylesheet"> {% endcomment %}
  </head>
  <body class="d-flex h-100 text-center text-black bg-white">
    
    {% comment %} <div class="cover-container d-flex w-100 h-100  mx-auto flex-column"> {% endcomment %}
    <div class="container-fluid d-flex w-100 h-100  mx-auto flex-column">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
          <span class="fs-4">CS201 Quiz</span>
        </a>
  
  
        <ul class="nav nav-pills">
          <li class="nav-item"><a href="{% url 'quiz:userface' %}" class="nav-link " aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'quiz:assignment'  %}" class="nav-link">Quizzes</a></li>
        <li class="nav-item"><a href="{% url 'quiz:account'  %}" class="nav-link active">Account</a></li>
        <li class="nav-item"><a href="{% url 'quiz:message'  %}" class="nav-link">Message</a></li>
        <li class="nav-item"><a href="{% url 'forum:forum' 'All' %}" class="nav-link ">Forum</a></li>
        <li class="nav-item"><a href="#" class="nav-link" onclick="go()">Log out</a></li>
        </ul>
      </header>


  <div class="bd-example-snippet bd-code-snippet" style="margin-left:20%;margin-right:20%;position:relative;margin-top:40px;"  >
    <div class="bd-example ">
    <table class="table table-borderless" >
      <tbody>
        <tr >
          <th scope="row" >NetID</th>
          <td>{{user.username}}</td>
          {% comment %} <td>{{j.0|status}}</td> {% endcomment %}
          {% comment %} <td>{{n.1}}</td> {% endcomment %}
        </tr>
        <tr >
            <th scope="row" >Name</th>
            <td>{{student.student_name}}</td>
            {% comment %} <td>{{j.0|status}}</td> {% endcomment %}
            {% comment %} <td>{{n.1}}</td> {% endcomment %}
          </tr>
          <tr >
            <th scope="row" >Password</th>
            <td><a href="{% url 'simple_judge:change_password' %}"> <button type="button" class="btn btn-primary btn-sm" >Change Password</button></a></td>
          </tr>
          {% if admin %}
          <tr >
            <th scope="row" >Admin</th>
            <td><a href="{% url 'quiz:admin' %}"> <button type="button" class="btn btn-primary btn-sm" >Admin page</button></a></td>
          </tr>
          {% endif %}
    
      </tbody>
    </table>
  </div>
</div>



{% comment %} <footer class="mt-auto text-black-50" style="font-size:15px">
    <p>Supported by <a class="text-black">CS201 TA Team</a>. Contact Beilong Tang (<a class="text-black">bt132@duke.edu</a>) if you have problems.</p>
  </footer> {% endcomment %}
</div>


    
  </body>
</html>

code/quiz/templates/quiz/admin_assignment.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    {% comment %} <meta name="viewport" content="width=device-width+100, initial-scale=2.0"> {% endcomment %}
    <meta name="description" content="">
    <meta name="author" content="Beilong Tang">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Home Page</title>


{% load static %}
{% load my_tags%}

<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/css/bootstrap.min.css' %}">
<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/js/bootstrap.bundle.min.js' %}">
<link rel = "stylesheet" type ="text/css" href = "{% static 'simple_judge/cover.css' %}">
<link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">
<script type= "text/javascript"  src = "{% static 'quiz/function.js' %}"></script>
<script>function go(){var x = "{% url 'simple_judge:signout' %}";confirmation(x);}</script>

    <!-- Custom styles for this template -->
    {% comment %} <link href="cover.css" rel="stylesheet"> {% endcomment %}
  </head>
  <body class="d-flex h-100 text-center text-black bg-white">
    
    <div class="container-fluid d-flex w-100 h-100  mx-auto flex-column">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
          <span class="fs-4">CS201 Admin Page</span>
        </a>
  
  
        <ul class="nav nav-pills">
          <li class="nav-item"><a href="{% url 'quiz:userface' %}" class="nav-link " aria-current="page">Back</a></li>
          <li class="nav-item"><a href="{% url 'quiz:admin' %}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{% url 'quiz:admin_assignment'  %}" class="nav-link active">Quizzes</a></li>
          {% comment %} <li class="nav-item"><a href="#" class="nav-link" onclick="go()">Log out</a></li> {% endcomment %}
        </ul>
      </header>


      <div class="bd-example-snippet bd-code-snippet" style="margin-left:20%;margin-right:20%;position:relative;margin-top:40px;"  >
        <div class="bd-example ">
        <table class="table table-borderless" >
          <tbody>
            <thead>
                <tr class='table-primary'>
                  <th scope="col">Assignment</th>
                  <th scope="col">Finished</th>
                  <th scope="col">Almost (20)</th>
                  <th scope="col">Pass-Rate</th>
                  <th scope="col">Submit Times</th>
                  <th scope="col">Open Date</th>
                  <th scope="col">Due Date</th>
                </tr>
                </thead>
                {% for i,j,m,k,n,q in array %}
                        <tr >
                            <th scope="row"><a href= '{% url 'quiz:admin_quiz' i %}'>{{i}}</a></th>
                            <td>{{m}}/{{student_number}}</td>
                            <td>{{k}}/{{student_number}}</td>
                            <td>{{n}}</td>
                            <td>{{q}}</td>
                            <td>{{j.0}}</td>
                            <td>{{j.1}}</td>
                        
                        </tr>
                {%endfor%}
        
          </tbody>
        </table>
      </div>
    </div>
    




  <footer class="mt-auto text-black-50" style="font-size:15px">
    <p>Supported by <a class="text-black">CS201 TA Team</a>. Contact Beilong Tang (<a class="text-black">bt132@duke.edu</a>) if you have problems.</p>
  </footer>
</div>


    
  </body>
</html>

code/quiz/templates/quiz/assignment.html
<!doctype html>
<html lang="en" class="h-100">

<head>
  <meta charset="utf-8">
  {% comment %}
  <meta name="viewport" content="width=device-width+100, initial-scale=2.0"> {% endcomment %}
  <meta name="description" content="">
  <meta name="author" content="Beilong Tang">
  <meta name="generator" content="Hugo 0.98.0">
  <title>Quizzes</title>


  {% load static %}
  {% load my_tags%}

  <link rel="stylesheet" type="text/css" href="{% static 'quiz/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'quiz/bootstrap/js/bootstrap.bundle.min.js' %}">
  <link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">
  <script type="text/javascript" src="{% static 'quiz/function.js' %}"></script>
  <script>function go() { var x = "{% url 'simple_judge:signout' %}"; confirmation(x); }</script>


</head>

<body class="d-flex h-100 text-center text-black bg-white">

  <div class="container-fluid d-flex w-100 h-100  mx-auto flex-column">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
          <use xlink:href="#bootstrap" />
        </svg>
        <span class="fs-4">CS201 Quiz</span>
      </a>


      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'quiz:userface' %}" class="nav-link " aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'quiz:assignment' %}" class="nav-link active">Quizzes</a></li>
        <li class="nav-item"><a href="{% url 'quiz:account'  %}" class="nav-link">Account</a></li>
        <li class="nav-item"><a href="{% url 'quiz:message'  %}" class="nav-link">Message</a></li>
        <li class="nav-item"><a href="{% url 'forum:forum' 'All' %}" class="nav-link ">Forum</a></li>
        <li class="nav-item"><a href="#" class="nav-link" onclick="go()">Log out</a></li>
      </ul>
    </header>


    <div class="bd-example-snippet bd-code-snippet"
      style="margin-left:10%;margin-right:10%;position:relative;margin-top:40px;">
      <div class="bd-example ">
        <table class="table table-hover">
          <thead>
            <tr class='table-primary'>
              <th scope="col">Assignment</th>
              <th scope="col">Progress</th>
              <th scope="col">Passed</th>
              <th scope="col">Status</th>
              <th scope="col">Due (CST)</th>
            </tr>
          </thead>
          <tbody>
            {% for i, j, k, m , p in array %}

            {% if i == 'week7' %}
            <tr class="table-primary">
              <th scope="row"><a href='{% url 'quiz:quiz_new' m %}'>{{i}}</a></th>
              <td></td>
              <td></td>
              <td name='status'><strong></strong></td>
              <td></td>
            </tr>

            {% else %}

            <tr class="table-primary">
              <th scope="row"><a href='{% url  'quiz:quiz_new' m %}'>{{i}}</a></th>
              <td>{{k}}</td>
              <td>{{p}}</td>
              <td name='status'><strong>{{j.0|status}}</strong></td>
              <td>{{j.1}}</td>
            </tr>

            {% endif %}

            {% endfor %}
          </tbody>
        </table>

          {% if array|length == 7%}
          <p>Quiz 7 is released with the answers, and it will not be graded. It can be used as your review material for
            week7.</p>
        <p>In other words, no more quizzes😀. Appreciate your hard work 👍!</p>
          {% endif %}
        
        

        


        <script>
          var x = document.getElementsByName('status');
          for (var i = 0; i < x.length; i++) {
            if (x[i].innerText == 'Open') { x[i].style = 'color:green' }
            if (x[i].innerText == 'Closed') { x[i].style = 'color:orange' }
          }

        </script>
      </div>
    </div>



    {%comment%} <footer class="mt-auto text-black-50" style="font-size:15px">
      <p>Supported by <a class="text-black">CS201 TA Team</a>. Contact Beilong Tang (<a
          class="text-black">bt132@duke.edu</a>) if you have problems.</p>
    </footer> {% endcomment %}
  </div>



</body>

</html>

code/quiz/templates/quiz/message.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="Beilong Tang">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Messages</title>


{% load static %}
{%load my_tags%}
<link rel = "stylesheet" type ="text/css" href = "{% static 'quiz/bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'quiz/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">
<script type= "text/javascript"  src = "{% static 'quiz/function.js' %}"></script>
<script>function go(){var x = "{% url 'simple_judge:signout' %}";confirmation(x);}</script>

<script>
  function go_to_forum_post(id ,category){
    var week = category+1;

    var forum_post_url = "{% url 'forum:forum_post' 1 0 0 'filt' %}";
    forum_post_url = forum_post_url.replace('filt','Week'+week)
    sidebar_length = -1;
    to_forum_post(id,forum_post_url,sidebar_length);
  }
</script>




<link rel="icon" type="image/x-icon" href="{% static 'quiz/CS201.svg' %}">
</head>
  

    <body class="d-flex h-100 text-center text-black bg-white">
    
    <div class="container-fluid d-flex w-100 h-100 mx-auto flex-column ">

    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4">CS201 Quiz</span>
      </a>


      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'quiz:userface' %}" class="nav-link" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'quiz:assignment' %}" class="nav-link">Quizzes</a></li>
        <li class="nav-item"><a href="{% url 'quiz:account'  %}" class="nav-link">Account</a></li>
        <li class="nav-item"><a href="{% url 'quiz:message'  %}" class="nav-link active">Message</a></li>
        <li class="nav-item"><a href="{% url 'forum:forum' 'All' %}" class="nav-link ">Forum</a></li>
        
        <li class="nav-item"><a href="#" class="nav-link" onclick="go()">Log out</a></li>
      </ul>
    </header>

    <script>
              function deletemsg(id){
                var x = document.getElementById('delete');
                x.value = id ; 
                document.deleteform.submit();
              }

          </script>
    <div style="width:50%;margin-left:25%">
      {%for p,c,reply_author in post_and_comment %}
      
      
      <a href="#">
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p style='margin-bottom:2px'><a style='color:red'>{{c.author_name}}</a> 
          {%if c.reply == -1 %}
          commented in 
          {% else %}
          replied to <a style='color:red'>{{reply_author}}</a> in
          {%endif%}
        </p>
        
        <p style='margin-bottom:2px'><a style='color:blue'>{{p.category|show_category}}</a> <a style='color:green'>{{p.question_id|show_question}}</a> <button style='border:none;background:none' onclick='go_to_forum_post({{p.id}},{{p.category}})'><a href="#">{{p.title|truncatechars:50 }}</a></button> </p>

        <p style='margin-bottom:2px'> {{c.text|truncatechars:100 }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" onclick='deletemsg({{c.id}})'></button>
      </div>
    </a>
      {%empty%}
      <p>You have no new messages.</p>
      {%endfor%}
    </div>

    <form method='post' action="{%url 'quiz:message' %}" style='display:none' name='deleteform'>
      {%csrf_token%}
        <input name ='delete' value = 0 id='delete'>
    </form>

  
    {% comment %} <footer class="mt-auto text-black-50" style="font-size:15px">
    <p>Supported by <a class="text-black">CS201 TA Team</a>. Contact Beilong Tang (<a class="text-black">bt132@duke.edu</a>) if you have problems.</p>
    </footer> {% endcomment %}
</div>


    
  </body>
</html>